---
title: "NWU - Optentia Research Programme, R"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
```

<!-- https://chat.openai.com/chat/dd967c72-a49c-4f21-ab54-2e20284b6ab0 -->

# Intro {.sidebar}

This dashboard covers the course materials for this week. 
<br> <br>
I'll adapt the materials as we go, so I suggest to access the materials online when we consider them. 
<br> <br>
Please note that some materials from the `R` course of [Gerko Vink](https://www.gerkovink.com) are included (mostly for day 1). The original materials can be found [here](https://github.com/gerkovink/R).

---

This course will be taught by [Duco Veen](https://www.ducoveen.com/). <br>

---
# Quick Overview

## Column 1

### Outline

Hi we are going to develop a short course on programming with R. You will act as a data scientist teaching R to social scientist. To produce the lecture materials we will make use of a quarto presentation in the revealjs style. To produce practical exercises we will use quarto documents. The topic of the course will introduce:

1)	a short introduction into programming in R and the structure of R
2)	Simple models such as regressions and correlation
3)	A brief introduction in classical test theory and structural equation modelling 
4)	Data visualization

Besides introductory lectures and practicals, we will have time to apply what will be learned directly on course participants own data in the afternoons. 

### Daily schedule 

In the mornings we will have lectures and time for practical alternating. In the afternoon there is time to work on practicals, ask questions, and work on your own data. I'll try to help you where I can with your own projects.

<!-- | When?  |      | What?      | -->
<!-- |:--------|:-------|:-------------| -->
<!-- | 09.00 | 09.30  | Lecture | -->
<!-- | 09:30 | 10.15  | Practical | -->
<!-- | 10.15 | 10.45  | Discussion | -->
<!-- |       | **break** |            | -->
<!-- | 11.00 | 11.45  | Lecture | -->
<!-- | 11:45 | 12.30  | Practical | -->
<!-- | 14:00 | 14.30  | Discussion | -->
<!-- | 14:30 | 15:30 | Lecture | -->
<!-- |       | **break** |            | -->
<!-- | 15:45 | 16.30  | Practical | -->
<!-- | 16:30 | 17:00  | Discussion | -->



## Column 2

### How to prepare

#### Preparing your machine for the course

To get started with R, you will need to install both R and RStudio. 

#### Installing R

R is a free software environment for statistical computing and graphics. To install R, please follow the instructions for your operating system from the following link:

- [Download R](https://cran.r-project.org/)

#### Installing RStudio

RStudio is an integrated development environment (IDE) for R. It provides a user-friendly interface to work with R and makes it easier to organize your code and results. To install RStudio, please follow the instructions for your operating system from the following link:

- [Download RStudio](https://rstudio.com/products/rstudio/download/)

Make sure to install R first before installing RStudio. Once you have installed both, you are ready to start using R for data analysis and visualization. If you encounter any issues during the installation process, please do not hesitate to reach out for assistance.




# Introduction into R

## Column 1

### Introduction materials
We adapt the course as we go. To ensure that you work with the latest iteration of the course materials, we advice all course participants to access the materials online.

- Introduction: 
    - [Lecture 1:](content/01_Introduction/lecture_01.html) What are R and RStudio. Basic elements and objects. How to find help.
    - [Practical 1:](content/01_Introduction/practical_01.html) Working with R-scripts and R-projects.
    - [Lecture 2:](content/01_Introduction/lecture_02.html) Structure of R. Functionality. Loading in data. 
    - [Practical 2:](content/01_Introduction/practical_02.html) Practicing with getting data from R, storing it, loading it back in.


All lectures are in `html` format. Practicals are walkthrough files that guide you through the exercises. 


# Modelling basics

## Column 1

### Materials

- Basics, correlation, regression, summaries, reliability analysis: 
    - [Lecture 1:](content/02_modelling/lecture_01.html) Basic plotting, summary, correlation and regression and model comparison. 
    - [Practical 1:](content/02_modelling/practical_01.html) Basic plotting, summary, correlation and regression and model comparison. 
    - [Lecture 2:](content/02_modelling/lecture_01.html) Reliability analysis, Principal component analysis and exploratory factor analysis. 
    
    <!-- - [Lecture 2:](content/02_modelling/lecture_02.html)  -->


# Data Visualisaton

## Column 1

### Materials

- ggplot2: 
    - [Lecture 1:](content/03_data_visualisation/lecture_01.html) Visualisation using ggplot2 and basic plots.
    - [Practical 1:](content/03_data_visualisation/practical_01.html) 
    
    <!-- - [Lecture 2:](content/03_data_visualisation/lecture_02.html)  -->


# Structural Equation Modelling

## Column 1

### Materials

- lavaan: 
    - [Lecture 1:](content/04_SEMn/lecture_01.html) Intro to lavaan, CFA, modelfit, plotting your SEM models.
    - [Practical 1:](content/04_SEM/practical_01.html) 
    
    <!-- - [Lecture 2:](content/04_SEM/lecture_02.html) -->

